/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-07-27 08:15:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\" />\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("        <meta name=\"description\" content=\"\" />\r\n");
      out.write("        <meta name=\"author\" content=\"\" />\r\n");
      out.write("        <title>Coming Soon - Start Bootstrap Theme</title>\r\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"assets/favicon.ico\" />\r\n");
      out.write("        <!-- Font Awesome icons (free version)-->\r\n");
      out.write("        <script src=\"https://use.fontawesome.com/releases/v6.3.0/js/all.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <!-- Google fonts-->\r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" />\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Tinos:ital,wght@0,400;0,700;1,400;1,700&amp;display=swap\" rel=\"stylesheet\" />\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&amp;display=swap\" rel=\"stylesheet\" />\r\n");
      out.write("        <!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("        <link href=\"css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <!-- Background Video-->\r\n");
      out.write("        <video class=\"bg-video\" playsinline=\"playsinline\" autoplay=\"autoplay\" muted=\"muted\" loop=\"loop\"><source src=\"assets/mp4/bg.mp4\" type=\"video/mp4\" /></video>\r\n");
      out.write("        <!-- Masthead-->\r\n");
      out.write("        <div class=\"masthead\">\r\n");
      out.write("            <div class=\"masthead-content text-white\">\r\n");
      out.write("                <div class=\"container-fluid px-4 px-lg-0\">\r\n");
      out.write("                    <h1 class=\"fst-italic lh-1 mb-4\">Our Website is Coming Soon</h1>\r\n");
      out.write("                    <p class=\"mb-5\">We're working hard to finish the development of this site. Sign up below to receive updates and to be notified when we launch!</p>\r\n");
      out.write("                    <!-- * * * * * * * * * * * * * * *-->\r\n");
      out.write("                    <!-- * * SB Forms Contact Form * *-->\r\n");
      out.write("                    <!-- * * * * * * * * * * * * * * *-->\r\n");
      out.write("                    <!-- This form is pre-integrated with SB Forms.-->\r\n");
      out.write("                    <!-- To make this form functional, sign up at-->\r\n");
      out.write("                    <!-- https://startbootstrap.com/solution/contact-forms-->\r\n");
      out.write("                    <!-- to get an API token!-->\r\n");
      out.write("                    <form id=\"contactForm\" data-sb-form-api-token=\"API_TOKEN\">\r\n");
      out.write("                        <!-- Email address input-->\r\n");
      out.write("                        <div class=\"row input-group-newsletter\">\r\n");
      out.write("                            <div class=\"col\"><input class=\"form-control\" id=\"email\" type=\"email\" placeholder=\"Enter email address...\" aria-label=\"Enter email address...\" data-sb-validations=\"required,email\" /></div>\r\n");
      out.write("                            <div class=\"col-auto\"><button class=\"btn btn-primary disabled\" id=\"submitButton\" type=\"submit\">Notify Me!</button></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"invalid-feedback mt-2\" data-sb-feedback=\"email:required\">An email is required.</div>\r\n");
      out.write("                        <div class=\"invalid-feedback mt-2\" data-sb-feedback=\"email:email\">Email is not valid.</div>\r\n");
      out.write("                        <!-- Submit success message-->\r\n");
      out.write("                        <!---->\r\n");
      out.write("                        <!-- This is what your users will see when the form-->\r\n");
      out.write("                        <!-- has successfully submitted-->\r\n");
      out.write("                        <div class=\"d-none\" id=\"submitSuccessMessage\">\r\n");
      out.write("                            <div class=\"text-center mb-3 mt-2\">\r\n");
      out.write("                                <div class=\"fw-bolder\">Form submission successful!</div>\r\n");
      out.write("                                To activate this form, sign up at\r\n");
      out.write("                                <br />\r\n");
      out.write("                                <a href=\"https://startbootstrap.com/solution/contact-forms\">https://startbootstrap.com/solution/contact-forms</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Submit error message-->\r\n");
      out.write("                        <!---->\r\n");
      out.write("                        <!-- This is what your users will see when there is-->\r\n");
      out.write("                        <!-- an error submitting the form-->\r\n");
      out.write("                        <div class=\"d-none\" id=\"submitErrorMessage\"><div class=\"text-center text-danger mb-3 mt-2\">Error sending message!</div></div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Social Icons-->\r\n");
      out.write("        <!-- For more icon options, visit https://fontawesome.com/icons?d=gallery&p=2&s=brands-->\r\n");
      out.write("        <div class=\"social-icons\">\r\n");
      out.write("            <div class=\"d-flex flex-row flex-lg-column justify-content-center align-items-center h-100 mt-3 mt-lg-0\">\r\n");
      out.write("                <a class=\"btn btn-dark m-3\" href=\"#!\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                <a class=\"btn btn-dark m-3\" href=\"#!\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                <a class=\"btn btn-dark m-3\" href=\"#!\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Bootstrap core JS-->\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <!-- Core theme JS-->\r\n");
      out.write("        <script src=\"js/scripts.js\"></script>\r\n");
      out.write("        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->\r\n");
      out.write("        <!-- * *                               SB Forms JS                               * *-->\r\n");
      out.write("        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->\r\n");
      out.write("        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->\r\n");
      out.write("        <script src=\"https://cdn.startbootstrap.com/sb-forms-latest.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
